### ISSUE TITLE
attempt to concatenate a nil Value (field '?')

### ISSUE THREAD

**Issue by DrCookie01** [ultrahacx/ultra-keypackhack#2]
Hello I hope you can help me with the problem
![unknown](https://user-images.githubusercontent.com/112406510/187221973-a8641389-7ae5-4ba5-ab6b-11c42e59dfea.png)

**Comment by ultrahacx** [comment]
You probably passed incorrect parameter for time

**Comment by vIG4Ever** [comment]
> 

I've the same problem

this is my code

```lua
RegisterCommand('mgkeypad',function()
    TriggerEvent('ultra-keypadhack', 3, 90, function(outcome, reason)
        --  life: Number of lives player has. Min is 1 and max is 6.
        --  time: Time in seconds which player has. min and max time can be set in config.lua
        --  result: Reason is the reason of result. Result is an integer code which represents result.
        --  0: Hack failed by player
        --  1: Hack successful
        --  2: Time ran out and hack failed
        -- -1: Error occurred i.e. passed input or contents in config is wrong
    
        if outcome == 0 then
            ESX.ShowNotification('Hack failed '..reason, 'error')
        elseif outcome == 1 then
            ESX.ShowNotification('Hack successful', 'success')
        elseif outcome == 2 then
            ESX.ShowNotification('Timed out', 'error')
        elseif outcome == -1 then
            ESX.ShowNotification('Error occured '..reason, 'error')
        end
    end)
end)
```

**Comment by vIG4Ever** [comment]
> You probably passed incorrect parameter for time

?

**Comment by ImmercityRP** [comment]
Can confirm this did fix that exact same error for me. 

I copied/pasted the call to this hack from another script, and for some reason it didn't work. Still worked on the first script, but got jaksam's error on the second. Added jaksam's suggestion, now it works perfectly fine on both, no other changes made.

I was calling my max time value, the same way in both scripts.

**Comment by ultrahacx** [comment]
Megred #3 to fix the race condition. Thank you for informing and thanks to @jaksam1074 for the PR to fix it

**Comment by jaksam1074** [comment]
No problem 😉

**Comment by Jackbeegaming** [comment]
Hey I am still having this problem, i am using qbcore

**Comment by ResqDiver1317** [comment]
> Hey I am still having this problem, i am using qbcore

@Jackbeegaming 
While this fix appears to have been merged, an updated release was NOT done. You need to look at the client.lua in the code view here and copy line 232 and paste that into the client.lua you got from the release download. The release version has the `showTimer()` and then moves right into showing the timer, It needs the check that jaksam wrote put in. 

I made this change manually to my file and it works now. 

Also, I know this is an older issue but thanks @jaksam1074 for the fix!

**Comment by ResqDiver1317** [comment]
@ultrahacx Can you issue a new release that includes the fix jaksam made?
